### ISSUE TITLE
Obfuscate other sources code?

### ISSUE THREAD

**Issue by Virgula0** [viraintel/OWASP-ZSC#125]
Hi, great work!
I see that software with function obfuscate can obfuscate python, perl, php, ruby and javascript sources but could be possible in next versions obfuscate sources of other programming languages like c# c,c++ and others??

Thank you!

**Comment by Ali-Razmjoo** [comment]
Hello,

Yes it's possible, but right now I don't have any plans, if you have, feel free to share and discuss. also any PR will appreciated.

Regards.
